# Generated by Django 4.2.1 on 2023-06-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SwanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_updated', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='swanapp.taskstatus')),
            ],
        ),
        migrations.CreateModel(
            name='SwanSubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vel', models.FloatField()),
                ('dir', models.FloatField()),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='swanapp.taskstatus')),
                ('swan_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='swanapp.swantask')),
            ],
        ),
    ]
